Feat: Create Landing Component
turinghut/turinghut-website pull request #13
Opened 2020-07-18 09:44 UTC by abhishekthalatoty

This PR completes #2 ( Landing Component )

2020-07-20 14:02 UTC, pinnamanivenkat requested changes

2020-07-20 14:02 UTC, pinnamanivenkat commented on package.json
> +    "@material-ui/core": "^4.11.0",
Let's remove all ^ from the here. We wouldn't want random package-lock to be updated. Because, if it's working, we need not disturb it.

2020-07-20 14:02 UTC, pinnamanivenkat commented on src/components/LandingComponent.js
> +      <Grid xs={10} md={4} justify="center" container item>
When it's xs 10, what about the 2?
I suggest going with xs={12}

2020-07-20 14:02 UTC, pinnamanivenkat commented on src/components/LandingComponent.js
> +      <Grid xs={10} md={4} item>
md={8} xs={12}

2020-07-20 14:02 UTC, pinnamanivenkat commented on src/pages/index.js
> +    <LandingComponent />
Wouldn't need a div over here. Grid itself compiles to div

2020-07-20 14:02 UTC, pinnamanivenkat commented on src/components/LandingComponent.js
> +      style={{ height: '95vh' }}
What's up with the 5vh?

2020-07-20 14:13 UTC, keerthi-reddy commented on package.json
> +    "@material-ui/core": "^4.11.0",
Do we need to keep it in gitignore?

2020-07-20 14:48 UTC, abhishekthalatoty commented on src/pages/index.js
> +    <LandingComponent />
We'll be stacking up all the components here, and since we need to return a single element, wrapped it around a div.

2020-07-20 14:53 UTC, abhishekthalatoty commented on src/components/LandingComponent.js
> +      <Grid xs={10} md={4} justify="center" container item>
Since the Logo is taking 100% width, 10 is giving it spacing at both of the sides. 12 is making the Logo too big.

2020-07-20 15:04 UTC, pinnamanivenkat commented on package.json
> +    "@material-ui/core": "^4.11.0",
No. Never place package.json or package-lock.json in gitignore. They are the essential drivers.

2020-07-20 15:20 UTC, keerthi-reddy commented on package.json
> +    "@material-ui/core": "^4.11.0",
Okay

2020-07-21 16:07 UTC, pinnamanivenkat commented on src/pages/index.js
> +    <LandingComponent />
Got it. 
Naming renaming the functional component would make sense, I guess. But that's for another PR.

2020-07-23 04:36 UTC, pinnamanivenkat requested changes
```jsx
import React from 'react'
import { Grid, Typography } from '@material-ui/core'

import TuringhutLogo from '../assets/TuringhutLogo.svg'

export default function LandingComponent() {
  return (
    <Grid
      container
      justify="space-between"
      alignItems="center"
      style={{ height: '100vh', padding: '0 5vw 0 5vw' }}
    >

      <Grid xs={12} md={7} container item justify="center" alignItems="center" >
        <Typography variant="h4" align="center" >
          We are a group of people working together for the improvement of
          programming culture in VNRVJIET
        </Typography>
      </Grid>
      <Grid xs={12} md={5} justify="center" alignItems="center" container item>
        <TuringhutLogo style={{ maxWidth: '100%' }} />
      </Grid>
    </Grid>
  )
}
```
Try this?

2020-07-23 04:36 UTC, pinnamanivenkat commented on src/components/LandingComponent.js
> +export default function LandingComponent() {
Let's use kebab style for file names

2020-07-24 14:34 UTC, abhishekthalatoty commented on src/components/LandingComponent.js
> +export default function LandingComponent() {
sure, But can we do Pascal case for SVGs? the Gatsby plugin imports them as React Components by Capitalizing.

2020-07-24 14:46 UTC, abhishekthalatoty commented
> ```js-jsx
> import React from 'react'
> import { Grid, Typography } from '@material-ui/core'
> 
> import TuringhutLogo from '../assets/TuringhutLogo.svg'
> 
> export default function LandingComponent() {
>   return (
>     <Grid
>       container
>       justify="space-between"
>       alignItems="center"
>       style={{ height: '100vh', padding: '0 5vw 0 5vw' }}
>     >
> 
>       <Grid xs={12} md={7} container item justify="center" alignItems="center" >
>         <Typography variant="h4" align="center" >
>           We are a group of people working together for the improvement of
>           programming culture in VNRVJIET
>         </Typography>
>       </Grid>
>       <Grid xs={12} md={5} justify="center" alignItems="center" container item>
>         <TuringhutLogo style={{ maxWidth: '100%' }} />
>       </Grid>
>     </Grid>
>   )
> }
> ```
> 
> Try this?

Done, Made few changes for the direction.

2020-07-29 06:20 UTC, pinnamanivenkat approved these changes

2020-07-31 17:29 UTC, merged